title: ICG Innovation
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics: # Add your Google Analytics tracking ID here
theme: jekyll-theme-cayman
author: ICG Innovation

# Standard Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: pretty
