title: Innovation @ ICG
description: Innovation at the Institute of Cosmology and Gravitation
show_downloads: false
google_analytics: # Add your Google Analytics tracking ID here
theme: jekyll-theme-cayman
author: ICG Innovation
tagline: Cutting edge research, innovation and outreach in astrophysics and cosmology.

# Standard Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
  authors:
    output: true
    permalink: /author/:slug/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
